# Generated by Django 3.1.6 on 2021-02-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='airtable_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='method',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
