# Generated by Django 3.1.6 on 2021-02-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists_profiles', '0002_auto_20210207_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='therapist',
        ),
        migrations.AddField(
            model_name='method',
            name='therapist',
            field=models.ManyToManyField(null=True, related_name='methods', to='therapists_profiles.Therapist'),
        ),
    ]
